SET LINESIZE 1000;
SET PAGESIZE 50000;
SET HEADING OFF;
SET FEEDBACK OFF;
SET VERIFY OFF;
SET TRIMSPOOL ON;

-- Define output file
SPOOL users_info.csv

-- Print CSV Header
PROMPT HOSTNAME,DATE,USERNAME,USER_SID,LAST_LOGIN,LAST_PASSWORD_CHANGE,USER_PRIVILEGES,USER_GROUPS

SELECT
    SYS_CONTEXT('USERENV', 'HOST') || ',' ||
    TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') || ',' ||
    U.USERNAME || ',' ||
    NVL(S.SID, 'N/A') || ',' ||
    NVL(TO_CHAR((SELECT MAX(LOGON_TIME) 
                 FROM V$SESSION 
                 WHERE USERNAME = U.USERNAME), 'YYYY-MM-DD HH24:MI:SS'), 'Never') || ',' ||
    NVL(TO_CHAR(U.PASSWORD_CHANGE_DATE, 'YYYY-MM-DD HH24:MI:SS'), 'Unknown') || ',' ||
    NVL((SELECT LISTAGG(GRANTED_ROLE, '; ') WITHIN GROUP (ORDER BY GRANTED_ROLE) 
         FROM DBA_ROLE_PRIVS 
         WHERE GRANTEE = U.USERNAME), 'No Roles') || ',' ||
    NVL((SELECT LISTAGG(PRIVILEGE, '; ') WITHIN GROUP (ORDER BY PRIVILEGE) 
         FROM DBA_SYS_PRIVS 
         WHERE GRANTEE = U.USERNAME), 'No Sys Privs')
FROM DBA_USERS U
LEFT JOIN V$SESSION S ON U.USERNAME = S.USERNAME
ORDER BY U.USERNAME;

SPOOL OFF;
EXIT;
