SET LINESIZE 1000;
SET PAGESIZE 50000;
SET HEADING OFF;
SET FEEDBACK OFF;
SET VERIFY OFF;
SET TRIMSPOOL ON;

-- Define output file
SPOOL users_info.csv

-- Print CSV Header
PROMPT HOSTNAME,DATE,USERNAME,USER_SID,LAST_LOGIN,LAST_PASSWORD_CHANGE,USER_PRIVILEGES,USER_GROUPS

-- SQL Query to extract user information
SELECT
    SYS_CONTEXT('USERENV', 'HOST') AS HOSTNAME,
    TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS DATE,
    U.USERNAME,
    S.SID AS USER_SID,
    (SELECT MAX(LOGON_TIME) 
        FROM V$SESSION 
        WHERE USERNAME = U.USERNAME) AS LAST_LOGIN,
    TO_CHAR(U.PASSWORD_CHANGE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS LAST_PASSWORD_CHANGE,
    LISTAGG(GRANTED_ROLE, '; ') WITHIN GROUP (ORDER BY GRANTED_ROLE) AS USER_PRIVILEGES,
    LISTAGG(GRANTEE, '; ') WITHIN GROUP (ORDER BY GRANTEE) AS USER_GROUPS
FROM DBA_USERS U
LEFT JOIN V$SESSION S ON U.USERNAME = S.USERNAME
LEFT JOIN DBA_ROLE_PRIVS RP ON U.USERNAME = RP.GRANTEE
LEFT JOIN DBA_SYS_PRIVS SP ON U.USERNAME = SP.GRANTEE
GROUP BY U.USERNAME, S.SID, U.PASSWORD_CHANGE_DATE;

SPOOL OFF;
EXIT;
