SET LINESIZE 1000;
SET PAGESIZE 50000;
SET HEADING OFF;
SET FEEDBACK OFF;
SET VERIFY OFF;
SET TRIMSPOOL ON;

-- Define output file
SPOOL users_info.csv

-- Print CSV Header
PROMPT HOSTNAME,DATE,USERNAME,USER_SID,LAST_LOGIN,LAST_PASSWORD_CHANGE,USER_PRIVILEGES,USER_GROUPS

-- SQL Query to extract user information
WITH user_sessions AS (
    SELECT 
        USERNAME, 
        MAX(LOGON_TIME) AS LAST_LOGIN
    FROM V$SESSION 
    WHERE USERNAME IS NOT NULL
    GROUP BY USERNAME
),
user_roles AS (
    SELECT 
        GRANTEE AS USERNAME,
        LISTAGG(GRANTED_ROLE, '; ') WITHIN GROUP (ORDER BY GRANTED_ROLE) AS USER_PRIVILEGES
    FROM DBA_ROLE_PRIVS
    GROUP BY GRANTEE
),
user_sys_privs AS (
    SELECT 
        GRANTEE AS USERNAME,
        LISTAGG(PRIVILEGE, '; ') WITHIN GROUP (ORDER BY PRIVILEGE) AS USER_PRIVILEGES
    FROM DBA_SYS_PRIVS
    GROUP BY GRANTEE
)
SELECT 
    SYS_CONTEXT('USERENV', 'HOST') AS HOSTNAME,
    TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS DATE,
    U.USERNAME,
    S.SID AS USER_SID,
    TO_CHAR(US.LAST_LOGIN, 'YYYY-MM-DD HH24:MI:SS') AS LAST_LOGIN,
    TO_CHAR(U.PASSWORD_CHANGE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS LAST_PASSWORD_CHANGE,
    NVL(UR.USER_PRIVILEGES, 'No Roles') AS USER_PRIVILEGES,
    NVL(USP.USER_PRIVILEGES, 'No Sys Privs') AS USER_GROUPS
FROM DBA_USERS U
LEFT JOIN V$SESSION S ON U.USERNAME = S.USERNAME
LEFT JOIN user_sessions US ON U.USERNAME = US.USERNAME
LEFT JOIN user_roles UR ON U.USERNAME = UR.USERNAME
LEFT JOIN user_sys_privs USP ON U.USERNAME = USP.USERNAME;

SPOOL OFF;
EXIT;
